[project]
name = "enzyme-kinetics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kristofer Gonzalez-DeWhitt", email = "k.gonzalez.dewhitt@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "kgdlibs",
    "logurich",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "pydantic>=2.13.4",
    "pylint>=4.0.5",
    "scipy>=1.17.1",
    "scipy-stubs>=1.17.1.4",
    "tyro>=1.0.13",
]

[project.scripts]
enzyme-kinetics = "enzyme_kinetics.main:main"

[build-system]
requires = ["uv_build>=0.11.11,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
logurich = { git = "https://github.com/kdewhitt/logurich.git" }
kgdlibs = { git = "https://github.com/kdewhitt/kgdlibs.git" }

[dependency-groups]
dev = [
    "black>=26.3.1",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
    "ty>=0.0.35",
]
plotting = [
    "matplotlib>=3.10.9",
    "scipy>=1.17.1",
    "scipy-stubs>=1.17.1.4",
    "seaborn>=0.13.2",
]
