[project]
name = "enzyme-kinetics"
version = "0.1.1"
description = "Compute Michaelis-Menten enzyme kinetics."
readme = "README.md"
authors = [
    { name = "Kristofer Gonzalez-DeWhitt", email = "k.gonzalez.dewhitt@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "kgdlibs",
    "logurich",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "pydantic>=2.13.4",
    "rich>=15.0.0",
    "scipy>=1.17.1",
    "scipy-stubs>=1.17.1.4",
    "tyro>=1.0.13",
]

[project.scripts]
analyze = "enzyme_kinetics.main:main"
calibrate = "enzyme_kinetics.calibrate:main"

[build-system]
requires = ["uv_build>=0.11.11,<0.12.0"]
build-backend = "uv_build"

[tool.uv]
link-mode = "copy"

[tool.uv.sources]
kgdlibs = { git = "https://github.com/kdewhitt/kgdlibs.git" }
logurich = { git = "https://github.com/kdewhitt/logurich.git" }

[tool.ruff]
line-length = 99
exclude = [
    ".venv",
    "build",
    "dist",
    "legacy",
    "tests",
]

[tool.ruff.lint]
extend-select = [
    "B", # bugbear
    "C4", # comprehensions
    "COM812", # enforce trailing commas
    "D", # pydocstyle
    "E", # pycodestyle errors
    "F", # pyflakes
    "SIM", # simplify
    # "TCH", # type-checking imports
    "UP", # pyupgrade
    "W", # pycodestyle warnings
]

# common conflicts
ignore = ["D203", "D213"]

# allow `assert` in tests and `print()` in scripts
per-file-ignores = { "tests/*" = ["S101"], "scripts/*" = ["T201"] }

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false  # allow trailing commas

[dependency-groups]
dev = [
    "icecream>=2.2.0",
    "pylint>=4.0.5",
    "pytest>=9.0.3",
    "ruff>=0.15.14",
    "ty>=0.0.39",
]
